maintainer       "Webtrends"
maintainer_email "kendrick.martin@webtrends.com"
license          "All rights reserved"
description      "Installs and configures A10"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "1.0.17"
depends          "webpi"
depends          "iis"
depends          "windows"
depends          "wt_base"
depends          "ms_dotnet4"
supports         "windows"
