name                "wt_actioncenter_dd_webtrendsemaildemo"
maintainer          "Webtrends, Inc."
maintainer_email    "denis.makarenko@webtrends.com"
license             "All rights reserved"
description         "Installs/Configures Webtrends Demo email Harness plugin"
version             "1.1.6"
depends             "java"
depends             "runit"
depends						  "wt_portfolio_harness"