default['wt_realtimeapi']['user']         = "nobody" 
default['wt_realtimeapi']['group']        = "nogroup"
default['wt_realtimeapi']['download_url'] = "http://teamcity.webtrends.corp/guestAuth/repository/download/bt120/.lastSuccessful/realtimeapi-bin.tar.gz"
default['wt_realtimeapi']['port']         = "8082"
default['wt_realtimeapi']['java_opts']    = "-Xms1024m -Djava.net.preferIPv4Stack=true"