---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: <%= ENV['CHEF_VERSION'] || 'latest' %>
  install_strategy: once

client_rb:
    treat_deprecation_warnings_as_errors: true

verifier:
  name: inspec

platforms:
- name: amazon-linux
  driver_config:
    box: mvbcoding/awslinux
- name: centos-6
- name: centos-7
- name: debian-8
- name: debian-9
- name: fedora-latest
- name: freebsd-10
- name: freebsd-11
- name: opensuse-leap-42
- name: ubuntu-16.04
- name: ubuntu-18.04

suites:
- name: server_install
  run_list:
    - recipe[test::server_install]
