source 'https://rubygems.org'

gem 'berkshelf', '~> 4.3'
gem 'chef', '~> 12.12'
gem 'chefspec', '~> 4.7'
gem 'foodcritic', '~> 6.3'
gem 'kitchen-dokken', '~> 1.0'
gem 'kitchen-vagrant', '~> 0.20'
gem 'rake', '~> 11.2'
gem 'rubocop', '~> 0.41'
gem 'test-kitchen', '~> 1.10'
