default['wt_streamingconfigservice']['camConnString'] = ""
default['wt_streamingconfigservice']['masterConnString'] = ""
default['wt_streamingconfigservice']['includeUnmappedAnalyticsIds'] = ""
default['wt_streamingconfigservice']['port'] = ""
default['wt_streamingconfigservice']['download_url'] = ""
default['wt_streamingconfigservice']['user'] = "webtrends"
default['wt_streamingconfigservice']['group'] = "webtrends"
