maintainer       "Webtrends"
maintainer_email "kendrick.martin@webtrends.com"
license          "All rights reserved"
description      "Installs/Configures CAM IIS site"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "1.0.5"
supports         "windows"
depends          "iis"
depends          "windows"
depends          "ms_dotnet4"
depends			 "wt_base"
