#!/bin/sh

# Setup basic path information.
LOG_OUT="<%=File.join(@log_dir,"nimbus.out")%>"
LOG_ERR="<%=File.join(@log_dir,"nimbus.err")%>"
HOME_DIR="<%=@install_dir%>"

CMD="$HOME_DIR/bin/storm nimbus"

# Find current PID if any.
FOUND_PID=$(ps -ef | grep java | grep backtype.storm.daemon.nimbus | grep -v grep | awk '{print $2}')

# Check what the caller wants.
case "$1" in
    start)
        if [ "" = "$FOUND_PID" ]; then
            echo $CMD
            # Storm processes look for a conf/ directory relative
            # the processes start directory.
            cd $HOME_DIR
            # For compatibility with runit we cannot backgroud 
            # ourselves with a '&' at the end, though we do
            # need to exec.
            exec $CMD >$LOG_OUT 2>$LOG_ERR
        else 
            echo "Service already running"
            exit 1
        fi
        ;;
    stop)
        if [ "" = "$FOUND_PID" ]; then
            echo "Service not running, nothing to stop"
            exit 1
        else
            kill $FOUND_PID
            sleep 4
            # Find PID again to see if we need to use kill -9 termination.
            FOUND_PID=$(ps -ef | grep java | grep backtype.storm.daemon.nimbus | grep -v grep | awk '{print $2}')
            if [ "" != "$FOUND_PID" ]; then
                echo "Using kill did not work, sending kill -9 to process"
                kill -9 $FOUND_PID
            fi
            exit 0
        fi 
        ;;
    status)
        # Status is found via actual running processes, rather than
        # trusting the PID log file.
        if [ "" = "$FOUND_PID" ]; then
            echo "Not running"
            exit 1
        else
            echo "Running"
            exit 0
        fi
        ;;
    *)
        echo "usage: daemon {start|stop|status}" >&2
        exit 1
        ;;
esac
