name             "wt_viracocha"
maintainer       "Webtrends, Inc."
maintainer_email "hostedops@webtrends.com"
license          "Apache 2.0"
description      "Installs/Configures packages needed for Viracocha 1.0"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "1.1.0"
depends          "rbvmomi"
depends          "ruby"
depends          "build-essential"
