name                "wt_streamingapi"
maintainer          "Webtrends, Inc."
maintainer_email    "ivan.vonnagy@webtrends.com"
license             "All rights reserved"
description         "Installs/Configures Webtrends Streaming API Service"
long_description    IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version             "1.2.6"
depends             "java"
depends             "runit"
depends		    "wt_base"
