maintainer       "Webtrends"
maintainer_email "kendrick.martin@webtrends.com"
license          "All rights reserved"
description      "Installs and configures A10"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.0.1"
depends			 "iis"
depends 		 "windows"
depends			 "wt_base"
supports		 "windows"
