maintainer       "Webtrends"
maintainer_email "kendrick.martin@webtrends.com"
license          "All rights reserved"
description      "Installs/Configures SAUTH IIS site"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.1.4"
supports         "windows"
depends          "iis"
depends          "windows"
depends          "wt_base"
depends	         "ms_dotnet4"
depends		 	 "wt_cam"
