name                "wt_streamingconfigservice"
maintainer          "Webtrends, Inc"
maintainer_email    "mark.alexander@webtrends.com"
license             "All rights reserved"
description         "Installs/Configures the Webtrends Streaming Config Service"
long_description    IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version             "1.0.10"
depends             "java"
depends             "runit"
depends             "minitest-handler"
