name             "wt_base"
maintainer       "Webtrends Inc."
maintainer_email "david.dvorak@webtrends.com"
license          "All rights reserved"
description      "Base Webtrends libraries and resources"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "1.0.4"
supports         "ubuntu", ">= 10.04"
supports         "centos", ">= 6.0"
supports         "windows", ">= 6.1"
depends          "apt"
depends          "yum"
depends          "windows"
depends          "webpi"
depends          "iis", ">= 1.1.2"