name                "wt_actioncenter_dd_responsys"
maintainer          "Webtrends, Inc."
maintainer_email    "michael.parsons@webtrends.com"
license             "All rights reserved"
description         "Installs/Configures Webtrends Action Center Mangaement Service"
version             "1.1.4"
depends             "java"
depends             "runit"
depends						  "wt_portfolio_harness"