name                "wt_actioncenter_dd_responsys"
maintainer          "Webtrends, Inc."
maintainer_email    "denis.makarenko@webtrends.com"
license             "All rights reserved"
description         "Installs/Configures Responsys Harness plugin"
version             "1.1.10"
depends             "java"
depends             "runit"
depends		    "wt_portfolio_harness"