name                "wt_actioncenter_ds_streaming"
maintainer          "Webtrends, Inc."
maintainer_email    "michael.parsons@webtrends.com"
license             "All rights reserved"
description         "Installs/Configures Webtrends Action Center Mangaement Service"
version             "1.1.3"
depends             "java"
depends             "runit"
