name             "filezilla"
maintainer       "Tim Smith - Webtrends Inc."
maintainer_email "tim.smith@webtrends.com"
license          "Apache 2.0"
license          "All rights reserved"
description      "Installs/Configures FileZilla Client for Windows"
version          "1.0.1"
supports         "windows"
depends          "windows"