name             "wt_streaming_viz"
maintainer       "Webtrends"
maintainer_email "kendrick.martin@webtrends.com"
license          "All rights reserved"
description      "Installs/Configures Streams UI IIS site"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "1.1.19"
supports         "windows"
depends          "iis"
depends          "windows"
depends          "wt_base"
depends	         "ms_dotnet4"
