name                "wt_actioncenter_management_api"
maintainer          "Webtrends, Inc."
maintainer_email    "michael.parsons@webtrends.com"
license             "All rights reserved"
description         "Installs/Configures Webtrends Action Center Mangaement Service"
version             "2.0.2"
depends             "java"
depends             "runit"
