name                "wt_actioncenter_dd_exacttarget"
maintainer          "Webtrends, Inc."
maintainer_email    "denis.makarenko@webtrends.com"
license             "All rights reserved"
description         "Installs/Configures ExactTarget Harness plugin"
version             "1.1.4"
depends             "java"
depends             "runit"
depends		    "wt_portfolio_harness"