#!/bin/sh
####################################################################
# Get information about system
####################################################################
OS=`uname`
KERNEL=`uname -r`
ARCH=`uname -m`

if [ "${OS}" = "SunOS" ] ; then
                OS=Solaris
                ARCH=`uname -p`
                OSSTR="${OS} ${REV}(${ARCH} `uname -v`)"
elif [ "${OS}" = "AIX" ] ; then
                OSSTR="${OS} `oslevel` (`oslevel -r`)"
elif [ "${OS}" = "Linux" ] ; then
                if [ -f /etc/redhat-release ] ; then
                                DistroBasedOn='RedHat'
                                DIST=`cat /etc/redhat-release |sed s/\ release.*//`
                                PSUEDONAME=`cat /etc/redhat-release | sed s/.*\(// | sed s/\)//`
                                REV=`cat /etc/redhat-release | sed s/.*release\ // | sed s/\ .*//`
                elif [ -f /etc/SuSE-release ] ; then
                                DistroBasedOn='SuSe'
                                PSUEDONAME=`cat /etc/SuSE-release | tr "\n" ' '| sed s/VERSION.*//`
                                REV=`cat /etc/SuSE-release | tr "\n" ' ' | sed s/.*=\ //`
                elif [ -f /etc/mandrake-release ] ; then
                                DistroBasedOn='Mandrake'
                                PSUEDONAME=`cat /etc/mandrake-release | sed s/.*\(// | sed s/\)//`
                                REV=`cat /etc/mandrake-release | sed s/.*release\ // | sed s/\ .*//`
                elif [ -f /etc/debian_version ] ; then
                                DistroBasedOn='Debian'
                                DIST=`cat /etc/lsb-release | grep '^DISTRIB_ID' | awk -F=  '{ print $2 }'`
                                PSUEDONAME=`cat /etc/lsb-release | grep '^DISTRIB_CODENAME' | awk -F=  '{ print $2 }'`
                                REV=`cat /etc/lsb-release | grep '^DISTRIB_RELEASE' | awk -F=  '{ print $2 }'`
                fi
                if [ -f /etc/UnitedLinux-release ] ; then
                                DIST="${DIST}[`cat /etc/UnitedLinux-release | tr "\n" ' ' | sed s/VERSION.*//`]"
                fi
                readonly OS
                readonly DIST
                readonly PSUEDONAME
                readonly REV
                readonly KERNEL
                readonly ARCH
fi

cores=$(cat /proc/cpuinfo | grep processor | wc -l)
mem=$(awk '$1 == "MemTotal:" {printf "%1.2f", ($2/(1024))/1024}' /proc/meminfo)gb
mhz=$(cat /proc/cpuinfo |grep "cpu MHz"| head -n 1| awk '{printf "%1.0f",$4}')MHz

echo "DIST:$DIST - $PSUEDONAME VER:$REV KERNEL:$KERNEL Arch:$ARCH #CPU:$cores Mem:$mem"
exit 0

