#!/bin/bash
#
# Written By: Josh Behrends / Tim Smith
# Webtrends 2012
#
#
date=$(date)

if [ -f /etc/redhat-release ] ; then
        yumtmp="$(sudo mktemp)"
        yum="/usr/bin/yum"
        sudo $yum check-update > $yumtmp 2>&1
        number=$(sudo cat $yumtmp | egrep '(.i386|.x86_64|.noarch|.src)' | wc -l)
        updates=$(sudo cat $yumtmp | egrep '(.i386|.x86_64|.noarch|.src)') #If we wanted to do something a list of the updates, here they are!
        sudo rm -rf $yumtmp #cleanup
        echo "YUM: $number updates available at $date|updates_total=$number;0;0;0;"
        exit 0
elif [ -f /etc/debian_version ] ; then
                if [ -f /usr/lib/update-notifier/apt-check ] ; then
                        apttmp="$(mktemp)"
                        /usr/lib/update-notifier/apt-check > $apttmp 2>&1
                        number=$(cat $apttmp | cut -d ';' -f 1) #Get total number here
                        numbercrit=$(cat $apttmp | cut -d ';' -f 2) #Get critial here
                        rm -rf $apttmp #cleanup
                        echo "APT: $number packages available for upgrade ($numbercrit critical updates)|updates_total=$number;0;0;0; update_critical=$numbercrit;0;0;0;"
                        exit 0
                else
                        echo "apt-check is not installed! Please install the update-notifier-common package"
                        exit 3
                fi
fi

