#!/bin/sh
####################################################################
# Get Memcached current connections for Nagios
#
# Josh Behrends - 2012 Webtrends
#
####################################################################


#Setup Nagios exit codes
STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3


help () {

  echo "===================================="
  echo "check_memcached_connections"
  echo "===================================="
  echo "Author  : Josh Behrends - Webtrends"
  echo "Date    : 2/24/2011"
  echo "===================================="
  echo "Option:-"
  echo " -w* : # of connections to trigger a warning"
  echo " -c* : # of connections to trigger a critical alert"
  echo " -d  : Debug option"
  echo " * is require parameter"
  echo ""
  echo "Example: $ ./check_memcached_connections -w 25 -c 30"
  echo ""
  exit 0
}

#Grab values passed into the argurments and place in variables.
while getopts ":c:w:h" Option
do
  case $Option in
    w )
      WARNING=$OPTARG
      ;;
    c )
      CRITICAL=$OPTARG
      ;;
    h )
      help
      ;;
  esac
done
shift $(($OPTIND - 1))

# Check parameters to make sure they actually contain values.  If not, show the help
[ -z $WARNING ] && help
[ -z $CRITICAL ] && help

#Find the location of the memcached-tool binary.
memcachedtool_bin=$(find /usr/ -name memcached-tool)

#Get the current number of connections to memcached
current_connections=$($memcachedtool_bin 127.0.0.1:11211 stats |awk '/curr_connections/ {printf "%1.0f",$2}')

# Normal status
if [ $current_connections -lt $WARNING ] ; then
        echo "OK - Memcached current connections: $current_connections|memcached_cur_conn=$current_connections;$WARNING;$CRITICAL;0;"
        exit $STATE_OK
# Warning status
elif [ $current_connections -lt $CRITICAL ] ; then
        echo "Warning - Memcached current connections: $current_connections|memcached_cur_conn=$current_connections;$WARNING;$CRITICAL;0;"
        exit $STATE_WARNING
# Critical status
elif [ $current_connections -gt $CRITICAL ] ; then
        echo "Critical - Memcached current connections: $current_connections|memcached_cur_conn=$current_connections;$WARNING;$CRITICAL;0;"
        exit $STATE_CRITICAL
fi

