name                "wt_streamingmanagementservice"
maintainer          "Webtrends, Inc"
maintainer_email    "ivan.vonnagy@webtrends.com"
license             "All rights reserved"
description         "Installs/Configures the Webtrends Streaming Management Service"
long_description    IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version             "1.0.3"
depends             "java"
depends             "runit"
depends             "minitest-handler"