name             "webtrends_server"
maintainer       "Webtrends Inc."
maintainer_email "hostedops@webtrends.com"
license          "All rights reserved"
description      "Installs/Configures the base Webtrends server setup"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "1.9.2"
supports         "windows"
supports         "ubuntu"
supports         "centos"
depends          "ad-auth"
depends          "apt"
depends          "chef-client"
depends          "collectd"
depends          "delltools"
depends          "hp-tools"
depends          "hosts"
depends          "man"
depends          "nagios"
depends          "networking_basic"
depends          "ntp"
depends          "openssh"
depends          "resolver"
depends          "rundeck"
depends          "selinux"
depends          "snmp"
depends          "sudo"
depends          "ubuntu"
depends          "vim"
depends          "vmware-tools"
depends          "windows"
depends          "wt_monitoring"
depends          "yum"