maintainer       "Webtrends, Inc."
maintainer_email "Peter Crossley <peter.crossley@webtrends.com>"
license          "All rights reserved"
description      "Installs/Configures Rundeck"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.rdoc'))
version          "1.0.6"
depends          "runit"
depends          "sudo"
depends          "java"
depends          "apache2"
