default[:user]         = "nobody"
default[:group]        = "nogroup"
default[:java_home]    = "/usr/lib/jvm/java-7-oracle/jre"
default[:download_url] = "http://teamcity.webtrends.corp/guestAuth/repository/download/bt75/.lastSuccessful/streamingcollection-bin.tar.gz"
default[:tarball]      = "streamingcollection-bin.tar.gz"