name             "wt_portfolio_manager"
maintainer       "Webtrends, Inc."
maintainer_email "toby.mosby@webtrends.com"
license          "All rights reserved"
description      "Installs/Configures Portfolio Manager IIS site"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "1.1.16"
supports         "windows"
depends          "iis"
depends          "windows"
depends          "wt_base"
depends          "ms_dotnet4"