name             "wt_logpreproc"
maintainer       "Webtrends"
maintainer_email "Jeremy.Chartrand@WebTrends.com"
license          "All rights reserved"
description      "Installs/Configures Webtrends Log Preprocessor"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version "1.0.16"
depends          "wt_base"
depends          "windows"
supports         "windows"
