maintainer       "Webtrends Inc"
maintainer_email "hostedops@webtrends.com"
license          "All rights reserved"
description      "Installs/Configures ondemand_base"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.rdoc'))
version          "0.0.1"
depends		 "ubuntu"
depends		 "ntp"
depends		 "openssh"
depends		 "sudo"
depends		 "vim"
depends		 "man"
depends		 "ad-likewise"
depends		 "users"
depends		 "networking_basic"
depends		 "users"
