maintainer       "Webtrends Inc"
maintainer_email "hostedops@webtrends.com"
license          "All rights reserved"
description      "Installs/Configures ondemand_base"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.rdoc'))
version          "1.4.0"
depends          "ad-auth"
depends          "chef-client"
depends          "hosts"
depends          "man"
depends          "nagios"
depends          "networking_basic"
depends          "ntp"
depends          "openssh"
depends          "resolver"
depends          "rundeck"
depends          "selinux"
depends          "snmp"
depends          "sudo"
depends          "ubuntu"
depends          "vim"
depends          "vmware-tools"
depends          "windows"
depends          "yum"